// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWxGzyoI_n_lA77CdlW_f6rF5gnxeJ6t8',
    appId: '1:951619617188:web:6287d4252795fd1ec68131',
    messagingSenderId: '951619617188',
    projectId: 'swasthya-setu-b3039',
    authDomain: 'swasthya-setu-b3039.firebaseapp.com',
    storageBucket: 'swasthya-setu-b3039.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUwDg5ZrddzO1-444Qe7IcomCXTpStQv0',
    appId: '1:951619617188:android:73438630234898d8c68131',
    messagingSenderId: '951619617188',
    projectId: 'swasthya-setu-b3039',
    storageBucket: 'swasthya-setu-b3039.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQFrSFNyVYeuEqK7x6C4HdVbtCQdWVYA4',
    appId: '1:951619617188:ios:3815e5419a30b550c68131',
    messagingSenderId: '951619617188',
    projectId: 'swasthya-setu-b3039',
    storageBucket: 'swasthya-setu-b3039.appspot.com',
    iosBundleId: 'com.example.swasthyaSetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQFrSFNyVYeuEqK7x6C4HdVbtCQdWVYA4',
    appId: '1:951619617188:ios:424734e4e76c0d34c68131',
    messagingSenderId: '951619617188',
    projectId: 'swasthya-setu-b3039',
    storageBucket: 'swasthya-setu-b3039.appspot.com',
    iosBundleId: 'com.example.swasthyaSetu.RunnerTests',
  );
}
